### ISSUE TITLE
Add Astral Sorcery to excluded mods list

### ISSUE THREAD

**Issue by kitsu** [KidsDontPlay/Yunifier#13]
I just had a very confusing time trying to advance in Astral Sorcery.
I needed to craft some runed marble, but every time I crafted any kind of marble (brick, column, chiseled) it almost instantly reverted to plain marble... It was like the items were losing their metadata.
At first I thought it was a Chisel mod incompatibility, but I couldn't find any evidence.
Then I remembered I had InstantUnify.

Adding `astralsorcery` to blacklisted mods (and adding `.*Marble.*` to the oredict blacklist) fixed my problem.
Since Astral Sorcery doesn't add anything that needs unification it should be safe to add to the default config.

MC: 1.12.2
Forge: 14.23.1.2587
InstantUnify: 1.1.1
Astral Sorcery: 1.8.4

**Comment by KidsDontPlay** [comment]
ok
