### ISSUE TITLE
Duplication of unifying certain blocks. 

### ISSUE THREAD

**Issue by Andyghandi** [KidsDontPlay/Yunifier#15]
When mining for example uranium, the unifying isnt stacking just in one stack, its divided into 2 ore sometimes 3 different stacks, even though the uranium from different mods is unified to immersive engineerings uranium. Also just regular mined stone is divided into different stacks and wont just stack in 1 stack up to 64 blocks. There probably are more blocks that behave this way, but this is what i have seen from testing. 
![2018-10-07_12 45 21](https://user-images.githubusercontent.com/25442543/46580959-877a1a00-ca2f-11e8-8370-e07f3b2b9086.png)

And I cant add the different stacks onto each other, even though i throw the "same" blocks on the ground and them pick them up. Any ideas what causes this?

**Comment by Andyghandi** [comment]
Also copper, tin and lead does the same thing.

**Comment by KidsDontPlay** [comment]
are you sure that this is caused by my mod?
instant unify doesn't affect cobblestone (unless you added it to the config).
show your config file

edit: do you use unidict?

**Comment by Andyghandi** [comment]
Its pretty hard to determine if this issue is caused by this mod, because if i try without it, all the ores drops as intended from respective mod. I havnt configured this mod, nor unidict, which im using too. I just figured this might be the place to start since it changes the block output from all ores into 1.

**Comment by Andyghandi** [comment]
Reinstalled this mod and for the moment things seem to work as intended with unifying ores. Not sure why it behaved the way it did. I will do further testing

Edit: Problem still remains. It just all of a sudden switches onto a new stack with the recent one stopping at like 13 or 5 or low numbers like that.

Edit 2: I can confirm that even torches doesn't stack in on stack either. This is the only thing relevant in the game log: "Received passengers for unknown entity". This pops up now and then and kinda matches in time when a new stack is started.

Edit 3: After some time goes, i suddenly can inventory sort which makes every item go together in one stack slot.. This is really confusing.

**Comment by LemADEC** [comment]
sounds like you've different NBT added to your items, by another mod
