### ISSUE TITLE
Trade Problem

### ISSUE THREAD

**Issue by KenyMylankca** [KidsDontPlay/Yunifier#16]
im directly saying the problem, sapphire from ice and fire wanted by a villager, and you unified the sapphire to biomes op's sapphire, and that villager doesn't accept bop sapphire, he wants ice and fire sapphire. please help this.

**Comment by KidsDontPlay** [comment]
add `gemSapphire` to the blacklist in the config file

**Comment by KenyMylankca** [comment]
but i want it be unified. i don't want 2 different sapphires. i'm playing it as it is at the moment, and hope you provide a fix that will let me choose which gem be the basic one.(ice and fire's sapphire instead of bop sapphire)

**Comment by KidsDontPlay** [comment]
then add the modid from ice and fire to `preferredMods`

**Comment by KenyMylankca** [comment]
but won't it unify all the things from ice and fire? cus it has also silver ingot, silver nugget, etc
