### ISSUE TITLE
unifier is a bit too aggressive with rods

### ISSUE THREAD

**Issue by mailleseraph** [KidsDontPlay/Yunifier#17]
This mod turns tool rods from tinkers' construct into the default Oredict rod(in my case immersive engineering iron rods) I disabled rod unifying because of that, maybe that could be something to check for, or add tinkers to the default excluded configs?

**Comment by MinhazMurks** [comment]
So you managed to fix this by removing rod.* from the config?

**Comment by SternyBeatbox** [comment]
was a solution for this ever found. i've tried multiple things with the config, but all tinkers tool rods turn into iron rods
