### ISSUE TITLE
Problem with plants and Yellorite ore

### ISSUE THREAD

**Issue by digi-tal-it** [KidsDontPlay/Yunifier#2]
I am on MC 1.12.1 and I have a strange issue when I try to harvest a plant. All plants are transformed to "blue orchid" after harvesting. I can reproduce it with Minecraft Plants and the latest plants mod (https://minecraft.curseforge.com/projects/plants?gameCategorySlug=mc-mods&projectID=257229) 
Plants from biomes o plenty and Pams Harvestcraft don't seem to be affected.

I also discovered, that yellorite ore from extrem reactors is transformed if put in a furnace to uranium ingot from Immersive Engineering. If i throw yellorite ore in a pulverizer and get yellorium dust, i can smelt it to yellorium ingot as it is supposed to be.

https://imgur.com/a/PNw4y

**Comment by KidsDontPlay** [comment]
the problem with flower is that the plants mod registers every flower in oredictionary. you can solve the problem by adding `plant` to the blacklist in config file.

the second one is not my fault. I don't change any furnace or pulverizer recipes.

**Comment by MokahTGS** [comment]
Yeah the same thing happens with workbenches from tinkers and cyclic.

I think there should be a whitelist by default and not just swap everything that isn't on the blacklist...especially since you can't change the config in game.  Makes for finding problems with large mod packs a pain.

**Comment by digi-tal-it** [comment]
Can you tell me where exactly I have to put the "plants".

I edited the instantunify.cfg on my server and tried adding plant in the S:blacklist array for OreDict names that shouldn't be unified. 

Or do you mean to blacklist the plants mod in row 5 ? How do I blacklist the minecraft plants? The show this behaviour, too.

**Comment by KidsDontPlay** [comment]
do you use the new version? If so, you should delete the config file.
the new version uses a whitelist instead

**Comment by digi-tal-it** [comment]
I installed the newest version on my server, deleted the config file and restarted it.
The problem still persists, this is the .conf file, that was generated.

# Configuration file

general {
    # Blacklisted Mods [default: ]
    S:blacklistMods <
     >

    # Preferred Mods [default: [thermalfoundation], [immersiveengineering], [embers]]
    S:preferredMods <
        thermalfoundation
        immersiveengineering
        embers
     >

    # Use UniDict's favorite ores to unify. [default: true]
    B:useUnidict=true
}


list {
    # OreDict names that shouldn't be unified. (supports regex) [default: [.*Wood], [.*Glass], [stair.*], [fence.*], [plank.*], [slab.*]]
    S:blacklist <
        .*Wood
        .*Glass
        stair.*
        fence.*
        plank.*
        slab.*
     >

    # true - use whitelist
    # false - use blacklist [default: true]
    B:useWhitelist=true

    # OreDict names that should be unified. (supports regex) [default: [block.*], [chunk.*], [dust.*], [dustSmall.*], [dustTiny.*], [gear.*], [gem.*], [ingot.*], [nugget.*], [ore.*], [plate.*], [rod.*]]
    S:whitelist <
        block.*
        chunk.*
        dust.*
        dustSmall.*
        dustTiny.*
        gear.*
        gem.*
        ingot.*
        nugget.*
        ore.*
        plate.*
        rod.*
     >
}


unifyevent {
    # Unify when items drop. [default: true]
    B:drop=true

    # Unify when GUI is opened/closed. [default: true]
    B:gui=true

    # Unify when blocks are harvested. [default: true]
    B:harvest=true

    # Unify every second items in player's inventory. [default: false]
    B:second=false
}

**Comment by digi-tal-it** [comment]
Here it is in a pastebin:

https://pastebin.com/zCxLXcd9

**Comment by KidsDontPlay** [comment]
so what's the problem? the whitelist is used by default (see `B:useWhitelist=true`).
therefore plants won't be unified anymore.
to add plants to the blacklist just add it like [this](https://pastebin.com/wYBFbZVU) but that's not necessary if you use whitelist

**Comment by KidsDontPlay** [comment]
wait, I'm an idiot

**Comment by KidsDontPlay** [comment]
fixed in 1.0.4

**Comment by digi-tal-it** [comment]
I can confirm, it works! Thanks for your work!
