### ISSUE TITLE
Add config option to disable/enable the unifying of liquids.

### ISSUE THREAD

**Issue by KittyKitCatCat** [KidsDontPlay/Yunifier#20]
I've had this happen many times, either in a tconstruct smeltery, a immersive engineering 2 machine or even a dimension made out of a liquid i specifically needed. Liquid is turned into different liquid, which is useless for what i was trying to do. Tic alloying requires specific alloys, immersive engineering diesel generator requires immersive petro… diesel or biodiesel, and im sure there is many more examples that i haven't encountered.

**Comment by KidsDontPlay** [comment]
this mod doesn't unifiy liquids
