### ISSUE TITLE
[BUG] v1.0.2 Scrambles tags

### ISSUE THREAD

**Issue by Nachtflame** [KidsDontPlay/Yunifier#22]
Noticed due to TNT dropping when I mined Aluminum Ore.  TNT suddenly had the tag [forge:ores/aluminum].  Diagnosed as issue with your mod by rolling back to v1.0.1, and errant tags immediately vanished.

Expect alot more reports on this from many sources.

**Comment by KidsDontPlay** [comment]
Oops
