### ISSUE TITLE
Port of 1.16

### ISSUE THREAD

**Issue by Switch-Back18** [KidsDontPlay/Yunifier#27]
Hello !

Did you port this mod in 1.16 ?

Thank you !

**Comment by OneLemonyBoi** [comment]
@MathisSkate https://www.curseforge.com/minecraft/mc-mods/blockdrops

**Comment by Switch-Back18** [comment]
That not works the url is break

**Comment by OneLemonyBoi** [comment]
i removed as was too laggy

**Comment by OneLemonyBoi** [comment]
https://www.curseforge.com/minecraft/mc-mods/instantunify+

**Comment by OneLemonyBoi** [comment]
@MathisSkate

**Comment by Switch-Back18** [comment]
that not works too

**Comment by OneLemonyBoi** [comment]
sorry, wrong link
https://www.curseforge.com/minecraft/mc-mods/instant-unify

**Comment by Switch-Back18** [comment]
Thank's !!

**Comment by Switch-Back18** [comment]
It's works like unidict he force the output of machine to the prefered tags or not ?

**Comment by OneLemonyBoi** [comment]
it works like this mod, so no
