### ISSUE TITLE
Unified Items Compatibility

### ISSUE THREAD

**Issue by MokahTGS** [KidsDontPlay/Yunifier#3]
Not sure what to do with this as it could be the other mod but is there a way to get Unified Items materials to work with this?  Aluminum ore is the specific issue (although there could be more) as it has two entries for the OreDictionary one under oreAluminum and another under oreAluminium.

Can I add it somehow or is that something you have to do?

**Comment by KidsDontPlay** [comment]
Currently only 'ores' with one entry can be unified, but I can fix it

**Comment by MokahTGS** [comment]
Alright. Thanks
