### ISSUE TITLE
[1.12.1] Too Many Chicken Mod Nuggets...

### ISSUE THREAD

**Issue by MokahTGS** [KidsDontPlay/Yunifier#4]
Is there any way to automagically setup nuggets from this mod to just use the preferred mod nuggets?  Currently the nuggets produced by the TMC mod uses the ore dictionary but there isn't an event that catches the nuggets when they are in an automated system.  I'm not sure how to convert them other than just take them out of the storage drawers and toss them on the ground.

**Comment by KidsDontPlay** [comment]
if you want to get nuggets form a specific mod just add the mod ID to preferredMods in config file in the first place.
My mod is not made for converting items that are already in chests or other inventory systems. It's made for converting when getting items.
