### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by totte1015** [KidsDontPlay/Yunifier#5]
I have Chisel, and instantunfy makes chiseled glass into regular glass... Its working good except this issue

In config it states glass is excepted buuut...

**Comment by totte1015** [comment]
Hello?

**Comment by KidsDontPlay** [comment]
which version do you use?

**Comment by KidsDontPlay** [comment]
Hello?

**Comment by totte1015** [comment]
Helloooo!

I disabled/deleted "*blocks" from the config and that seemed to fix it

Using 1.10.2 latest one!
