### ISSUE TITLE
Future Pack!

### ISSUE THREAD

**Issue by CluelessPhil** [KidsDontPlay/Yunifier#8]
Hello so im addign this mod to my modpack and FutrePack doesnt use OreDict ingots so how can i remove their ores from the unify the name is 'fp:erze:1,2,3,4,5,6,7' (the numbers are for the different ores). How would i put this in the blacklist?

**Comment by KidsDontPlay** [comment]
What? I don't get it.
FuturePack doesn't use OreDict ingots. So why do you need this mod?
You can't blacklist item ids, only their oredict names.
It is possible to blacklist entire mods (`fp` in that case). this may help you

**Comment by CluelessPhil** [comment]
Yea I don’t know what I was say. Would I just do “fp*”?

**Comment by KidsDontPlay** [comment]
just put `fp` into `blacklistMods`
