### ISSUE TITLE
[1.12.2] configuration problems

### ISSUE THREAD

**Issue by Draskh** [KidsDontPlay/Yunifier#9]
I added aluminum bauxite to the configuration but bauxite does not get unified.

Second problem is that I added gravelores to the backlist but the gravel ores still get unified. 

So is the config file loaded?

**Comment by KidsDontPlay** [comment]
show the config file

**Comment by Draskh** [comment]
[instantunify.txt](https://github.com/MrRiegel/Yunifier/files/1589664/instantunify.txt) (converted to .txt because Github does not support .cfg) 

Undict is also present but it works for all other ores. The Gravel Ores are not blacklisted but I'm sure I have the correct modID.

**Comment by KidsDontPlay** [comment]
1. if unidict support is enabled and unidict is present, the settings of instantunify will be ignored.
`(Other settings from this mod will be ignored.)`

2. 
```
    S:alternatives <
        aluminum aluminium bauxite
     >
```
that's the correct way

**Comment by Draskh** [comment]
Will all setting be ignored if UniDict is present?

**Comment by Draskh** [comment]
It came out it is problem with TF that prevents registration. https://github.com/CoFH/Feedback/issues/833

**Comment by Draskh** [comment]
Seems that is not TF but I tested everything without Instant Unify, so it is not involved.
